{
 "title": "K8S集群资源总览",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "prometheus" },
   {
    "name": "env",
    "query": "label_values(kubernetes_build_info, env)"
   },
   {
    "name": "cluster",
    "label": "环境",
    "query": "label_values(kubernetes_build_info{env=\"$env\"}, cluster)"
   },
   {
    "name": "device",
    "label": "网卡",
    "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*',cluster=~\"$cluster\"},device)"
   },
   { "name": "interval", "query": "4h" },
   { "name": "resolution", "query": "30s,5m,1h" }
  ]
 },
 "panels": [
  { "title": "主页面", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "description": "$cluster环境K8s在线的计算资源节点数",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "个" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{env=\"$env\",cluster=\"$cluster\",job=\"kubelet\",metrics_path=\"/metrics\"}==1)",
     "legendFormat": "工作节点："
    },
    {
     "expr": "count(up{env=\"$env\",cluster=\"$cluster\",job=\"kubelet\",metrics_path=\"/metrics\"}!=1)",
     "legendFormat": "下线节点："
    }
   ]
  },
  {
   "type": "stat",
   "description": "此监控图描述k8s集群中$cluster环境部署的正常的无状态服务数量。无状态部署：k8s中的一种资源类型，适用于部署无状态服务。它管理容器组的版本与状态等，而容器组中运行的容器则是应用服务在k8s中真正运行的载体。",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "个" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_status_replicas_available{env=\"$env\",cluster=\"$cluster\",namespace=\"$cluster\"} > 0)",
     "legendFormat": "无状态服务正常："
    },
    {
     "expr": "count(kube_deployment_status_replicas_unavailable{env=\"$env\",cluster=\"$cluster\",namespace=\"$cluster\"} > 0) by (deployment)",
     "legendFormat": "无状态服务异常：{{deployment}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "此监控图描述k8s集群中$cluster环境部署的正常的有状态服务数量。有状态部署：k8s中的一种资源类型，适用于有状态服务的部署。它管理容器组的版本与状态等，而容器组中运行的容器则是应用服务在k8s中真正运行的载体。",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "个" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_statefulset_status_replicas_ready{env=\"$env\",job=\"kube-state-metrics\",cluster=\"$cluster\",namespace=\"$cluster\"})",
     "legendFormat": "有状态服务正常："
    },
    {
     "expr": "count(kube_statefulset_status_replicas_ready{env=\"$env\",job=\"kube-state-metrics\",cluster=\"$cluster\",namespace=\"$cluster\"}\r !=\r kube_statefulset_status_replicas{env=\"$env\",job=\"kube-state-metrics\",cluster=\"$cluster\",namespace=\"$cluster\"})",
     "legendFormat": "有状态服务异常："
    }
   ]
  },
  {
   "type": "stat",
   "description": "此监控图描述k8s集群中$cluster环境部署的正常的容器组数量。容器组：k8s中最小的管理单元，用于管理容器组中容器的生命周期，而容器则是应用服务在k8s中运行的载体。",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "个" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{env=\"$env\",cluster=\"$cluster\",namespace=\"$cluster\"}) - sum(kube_pod_status_phase{env=\"$env\",job=\"kube-state-metrics\", phase=~\"Pending|Unknown\",cluster=\"$cluster\",namespace=\"$cluster\"}) > 0",
     "legendFormat": "容器组正常："
    },
    {
     "expr": "sum(kube_pod_status_phase{env=\"$env\",job=\"kube-state-metrics\", phase=~\"Pending|Unknown\",cluster=\"$cluster\",namespace=\"$cluster\"}) > 0",
     "legendFormat": "容器组异常："
    },
    {
     "expr": "sum(kube_pod_status_ready{env=\"$env\",cluster=\"$cluster\",namespace=\"$cluster\"}) - sum(kube_pod_status_phase{env=\"$env\",job=\"kube-state-metrics\", phase=~\"Running|Pending|Unknown\",cluster=\"$cluster\",namespace=\"$cluster\"}) > 0",
     "legendFormat": "容器组异常："
    }
   ]
  },
  {
   "type": "stat",
   "description": "该视图显示当前$cluster环境中运行中容器的总数，容器是应用服务运行的载体。",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "个" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{env=\"$env\",cluster=\"$cluster\",namespace=\"$cluster\"})",
     "legendFormat": "运行中容器："
    }
   ]
  },
  {
   "title": "CPU 预分配总量",
   "type": "singlestat",
   "description": "$cluster集群CPU总预分配量，这代表当前已被预先分配掉的CPU资源百分比。",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{env=\"$env\",cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_cpu_cores{env=\"$env\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU 使用上限总量（参考）",
   "type": "singlestat",
   "description": "$cluster集群CPU使用上限限制，这代表当前集群CPU资源的使用上限百分比。",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{env=\"$env\",cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_cpu_cores{env=\"$env\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "内存预分配总量",
   "type": "singlestat",
   "description": "$cluster集群内存总预分配量，这代表当前已被预先分配掉的内存资源百分比。",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{env=\"$env\",cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{env=\"$env\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "内存使用上限（参考）",
   "type": "singlestat",
   "description": "$cluster集群内存使用上限限制，这代表当前集群内存资源的使用上限百分比。",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{env=\"$env\",cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{env=\"$env\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "$cluster集群资源总使用率",
   "type": "bargauge",
   "description": "当前集群资源使用率",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", env=~\"$env\", cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "CPU 使用率"
    },
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{env=\"$env\",cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{env=\"$env\",cluster=\"$cluster\"})",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{env=\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{env=\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{env=\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{env=\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{env=\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
     "legendFormat": "磁盘使用率"
    }
   ]
  },
  {
   "type": "stat",
   "description": "$cluster集群CPU资源总使用量",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(instance:node_cpu:rate:sum{env=~\"$env\",cluster=\"$cluster\"}) by (cluster)",
     "legendFormat": "$cluster集群CPU总使用量："
    }
   ]
  },
  {
   "type": "stat",
   "description": "$cluster集群内存资源总使用量",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{env=~\"$env\",cluster=\"$cluster\"}) - sum(:node_memory_MemAvailable_bytes:sum{env=~\"$env\",cluster=\"$cluster\"})",
     "legendFormat": "内存总已用："
    }
   ]
  },
  {
   "type": "stat",
   "description": "$cluster集群磁盘资源总使用量",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{env=~\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{env=~\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "磁盘总使用量："
    }
   ]
  },
  {
   "type": "stat",
   "description": "$cluster集群CPU资源总量",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{env=~\"$env\",cluster=\"$cluster\", mode=\"system\"})",
     "legendFormat": "总核数："
    }
   ]
  },
  {
   "type": "stat",
   "description": "$cluster集群内存资源总量",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{env=~\"$env\",cluster=\"$cluster\"})",
     "legendFormat": "总内存："
    }
   ]
  },
  {
   "type": "stat",
   "description": "$cluster集群磁盘资源总量",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{env=~\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "总磁盘量："
    }
   ]
  },
  {
   "title": "$cluster集群 各节点已预分配CPU资源（Requests CPU%）",
   "type": "table",
   "description": "$cluster环境各计算节点已预分配的CPU资源占比",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc((sum by (node) (kube_pod_container_resource_requests_cpu_cores{env=\"$env\",cluster=\"$cluster\"})) / (sum by (node) (kube_node_status_allocatable_cpu_cores{env=\"$env\",cluster=\"$cluster\"})))",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sort_desc( sum by (node) (kube_node_status_allocatable_cpu_cores{env=\"$env\",cluster=\"$cluster\"}) - (sum by (node) (kube_node_status_allocatable_cpu_cores{env=\"$env\",cluster=\"$cluster\"}) - sum by (node) (kube_pod_container_resource_requests_cpu_cores{env=\"$env\",cluster=\"$cluster\"})))",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{env=\"$env\",cluster=\"$cluster\"}) by (node)"
    },
    {
     "expr": "sort_desc(sum by (node) (kube_node_status_allocatable_cpu_cores{env=\"$env\",cluster=\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "$cluster集群 各节点已预分配内存资源（Requests Memory%）",
   "type": "table",
   "description": "$cluster环境各计算节点已预分配的内存资源占比",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (node) (kube_pod_container_resource_requests_memory_bytes{env=\"$env\",cluster=\"$cluster\"}) / sum by (node) (kube_node_status_allocatable_memory_bytes{env=\"$env\",cluster=\"$cluster\"}))",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sort_desc(sum by (node) (kube_node_status_allocatable_memory_bytes{env=\"$env\",cluster=\"$cluster\"}) - (sum by (node) (kube_node_status_allocatable_memory_bytes{env=\"$env\",cluster=\"$cluster\"}) - sum by (node) (kube_pod_container_resource_requests_memory_bytes{env=\"$env\",cluster=\"$cluster\"})))",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{env=\"$env\",container!=\"\",cluster=\"$cluster\"}) by (node)"
    },
    {
     "expr": "sum by (node) (kube_node_status_allocatable_memory_bytes{env=\"$env\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "$cluster集群CPU总使用量历史数据",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{env=\"$env\",cluster=\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}总使用量"
    },
    {
     "expr": "count(node_cpu_seconds_total{env=\"$env\",cluster=\"$cluster\", mode='system'})",
     "legendFormat": "{{cluster}}CPU总量"
    }
   ]
  },
  {
   "title": "$cluster集群Memory总使用量历史数据",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{env=\"$env\",cluster=\"$cluster\"}) - sum(node_memory_MemAvailable_bytes{env=\"$env\",cluster=\"$cluster\"})",
     "legendFormat": "$cluster集群内存总使用量"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{env=\"$env\",cluster=\"$cluster\"})",
     "legendFormat": "$cluster集群内存总量"
    }
   ]
  },
  {
   "title": "磁盘",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{env=\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{env=\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "总使用量"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{env=\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{env=\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{env=\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{env=\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{env=\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
     "legendFormat": "总平均使用率"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{env=\"$env\",cluster=\"$cluster\",fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "总磁盘量"
    }
   ]
  },
  {
   "title": "集群详情",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "$cluster集群计算资源",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(mixin_pod_workload{env=\"$env\",cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "count(avg(mixin_pod_workload{env=\"$env\",cluster=\"$cluster\"}) by (workload, namespace)) by (namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{env=\"$env\",cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{env=\"$env\",cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{env=\"$env\",cluster=\"$cluster\"}) by (namespace) / sum(kube_pod_container_resource_requests_cpu_cores{env=\"$env\",cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{env=\"$env\",cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{env=\"$env\",cluster=\"$cluster\"}) by (namespace) / sum(kube_pod_container_resource_limits_cpu_cores{env=\"$env\",cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss{env=\"$env\",cluster=\"$cluster\", container!=\"\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{env=\"$env\",cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss{env=\"$env\",cluster=\"$cluster\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_requests_memory_bytes{env=\"$env\",cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{env=\"$env\",cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss{env=\"$env\",cluster=\"$cluster\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_limits_memory_bytes{env=\"$env\",cluster=\"$cluster\"}) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_receive_bytes_total{env=\"$env\",cluster=\"$cluster\", namespace=~\".+\"}[$interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{env=\"$env\",cluster=\"$cluster\", namespace=~\".+\"}[$interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_total{env=\"$env\",cluster=\"$cluster\", namespace=~\".+\"}[$interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{env=\"$env\",cluster=\"$cluster\", namespace=~\".+\"}[$interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{env=\"$env\",cluster=\"$cluster\", namespace=~\".+\"}[$interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{env=\"$env\",cluster=\"$cluster\", namespace=~\".+\"}[$interval])) by (namespace)"
      }
     ]
    }
   ]
  }
 ]
}