{
 "title": "Nginx VTS Stats",
 "description": "Show stats from nginx VTS module",
 "tags": [
  "prometheus",
  "nginx",
  "kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nginx_server_info,instance)"
   },
   {
    "name": "httphost",
    "label": "HTTP Host",
    "query": "label_values(nginx_server_requests{instance=\"$instance\"}, host)"
   },
   {
    "name": "upstream",
    "label": "Upstream",
    "query": "label_values(nginx_upstream_requests,upstream)"
   },
   {
    "name": "code",
    "label": "状态码",
    "query": "label_values(nginx_upstream_requests,code)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nginx_vts_exporter_build_info{instance=\"$instance\"}",
     "legendFormat": "状态"
    }
   ]
  },
  {
   "title": "Current Response Code Per Second",
   "type": "grafana-piechart-panel",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nginx_server_requests{code!=\"total\",instance=\"$instance\",host=~\"$httphost\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Server Requests by Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_server_requests{instance=\"$instance\",host=~\"$httphost\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_server_requests{instance=\"$instance\",host=~\"$httphost\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Upstream Requests by Code",
   "type": "graph",
   "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_upstream_requests{instance=\"$instance\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Server Requests by Host",
   "type": "graph",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_server_requests{instance=\"$instance\", code=\"total\", host=~\"$httphost\"}[5m]) > 0) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Server Requests by Upstream",
   "type": "graph",
   "description": "Requests per second grouped by response code",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_upstream_requests{instance=\"$instance\", code=\"total\", upstream=~\"$upstream\"}[5m]) > 0) by (upstream)",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Average Server Request Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_server_requestMsec{instance=\"$instance\",host!=\"*\"} > 0) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Upstream request time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_upstream_requestMsec{instance=\"$instance\"} > 0) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_server_connections{instance=\"$instance\", status=~\"accepted|handled|requests|active|writing|reading|waiting\"}[10m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Upstream response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_upstream_responseMsec{instance=\"$instance\"} > 0) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Server Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_server_bytes{host=~\"$httphost\",instance=\"$instance\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Upstream throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_upstream_bytes{instance=\"$instance\",upstream=~\"$upstream\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Cache events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_server_cache{instance=\"$instance\", host=~\"$httphost\"}[5m])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  }
 ]
}